### ISSUE TITLE
Update all the current locations for how to report issues

### ISSUE THREAD

**Issue by feanil** [openedx/wg-security#13]
```[tasklist]
# Subtickets

- [ ] https://github.com/openedx/wg-security/issues/12
- [ ] Announce the security@openedx.org mailing list on discourse.
- [ ] https://github.com/openedx/wg-security/issues/2
```
